# Generated by Django 2.0 on 2017-12-15 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'verbose_name': 'Categoria',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('preco', models.CharField(max_length=50, null=True, verbose_name='Preço')),
                ('imagem', models.ImageField(blank=True, default='static/img/noperfil.png', null=True, upload_to='static/img/', verbose_name='Imagem')),
                ('quantidade', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('data_cadastro', models.DateField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
                ('categoria', models.ManyToManyField(to='core.Categoria')),
            ],
            options={
                'verbose_name_plural': 'Produtos',
                'verbose_name': 'Produto',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('administrador', models.BooleanField(verbose_name='ADM')),
                ('perfil', models.CharField(max_length=500, verbose_name='Perfil')),
                ('imagem_perfil', models.ImageField(blank=True, default='img/usuarios/noperfil.png', null=True, upload_to='img/usuarios/', verbose_name='Imagem de Perfil')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
                ('residencial', models.CharField(max_length=11, verbose_name='Residêncial')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
                'verbose_name': 'Usuario',
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
