# Generated by Django 2.0 on 2017-12-13 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, default='static/img/noperfil.png', null=True, upload_to='static/img/', verbose_name='Imagem')),
                ('quantidade', models.IntegerField(null=True, verbose_name='Quantidade')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('administrador', models.BooleanField(verbose_name='ADM')),
                ('imagem_perfil', models.ImageField(blank=True, default='img/usuarios/noperfil.png', null=True, upload_to='img/usuarios/', verbose_name='Imagem de Perfil')),
                ('email', models.CharField(max_length=100, verbose_name='E-mail')),
                ('celular', models.CharField(max_length=11, verbose_name='Celular')),
                ('senha', models.CharField(max_length=100, verbose_name='senha')),
                ('residencial', models.CharField(max_length=11, verbose_name='Residêncial')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.AddField(
            model_name='produtos',
            name='cpf_vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_produto', to='core.Usuario'),
        ),
    ]
