# Generated by Django 2.0 on 2017-12-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de Início')),
                ('imagem', models.ImageField(blank=True, default='img/cursos/noperfil.png', null=True, upload_to='img/cursos/', verbose_name='Imagem')),
                ('vagas', models.IntegerField(verbose_name='Vagas')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_modificacao', models.DateField(auto_now=True, verbose_name='Data de Modificação')),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
