# Generated by Django 2.0 on 2017-12-13 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171213_1635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categorias', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='cpf_vendedor',
        ),
        migrations.AddField(
            model_name='produtos',
            name='preco',
            field=models.CharField(max_length=50, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
    ]
