# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171206_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='produtos',
            name='vagas',
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_chegada',
            field=models.DateField(blank=True, null=True, verbose_name='Chegada do Produto'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(default=1, verbose_name='Estoque'),
            preserve_default=False,
        ),
    ]
