# Generated by Django 2.0 on 2017-12-13 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171213_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_cadastro',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Cadastro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produtos',
            name='data_modificação',
            field=models.DateField(auto_now=True, verbose_name='Data de Modificação'),
        ),
    ]
