# Generated by Django 2.0 on 2017-12-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171213_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='data_modificação',
            field=models.DateField(auto_now=True, verbose_name='Data de Modificação'),
        ),
    ]
