# Generated by Django 2.0 on 2017-12-13 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_produtos_data_modificação'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='data_modificação',
        ),
    ]
